// Copyright 2026 Enlightware GmbH
// SPDX-License-Identifier: Apache-2.0

import { readFileSync } from 'node:fs';
import { performance } from 'node:perf_hooks';
import runtime from '../../target/wasm-profile/wasm_profile.js';

const { Workload } = runtime;

const source = process.argv[2] ? readFileSync(process.argv[2], 'utf8') : `
fn compute(iterations: int) -> int {
    let mut i = 0;
    let mut total = 0;
    loop {
        if i >= iterations { break; };
        total = total * 3 + i;
        i += 1;
    };
    total
}`;
const iterations = Number(process.argv[3] ?? 1000000);
if (!Number.isInteger(iterations) || iterations < 0 || iterations > 2147483647) {
    throw new Error('iterations must be a nonnegative i32');
}
let start = performance.now();
const workload = new Workload(source);
const compilation = performance.now() - start;
try {
    start = performance.now();
    workload.instantiate();
    const instantiation = performance.now() - start;
    for (let warmup = 0; warmup < 5; warmup++) workload.run(iterations);
    const samples = [];
    let result;
    for (let sample = 0; sample < 7; sample++) {
        start = performance.now();
        result = workload.run(iterations);
        samples.push(performance.now() - start);
    }
    samples.sort((a, b) => a - b);
    console.log(`Ferlium compile + emit: ${compilation.toFixed(3)} ms`);
    console.log(`Wasm compile + instantiate: ${instantiation.toFixed(3)} ms`);
    console.log(`Warmed execution (median): ${samples[3].toFixed(3)} ms`);
    console.log(`Iterations: ${iterations}; result: ${result}; generated bytes: ${workload.code_bytes()}`);
} finally {
    workload.free();
}
